#                   
# This source file is part of the Collector-Analyst-Presenter Example open source project
#
# SPDX-FileCopyrightText: 2021 Paul Schmiedmayer and the project authors (see CONTRIBUTORS.md) <paul.schmiedmayer@tum.de>
#
# SPDX-License-Identifier: MIT
#

version: "3.9"
services:
  jaeger:
    image: "jaegertracing/all-in-one"
    ports:
      - "14250:14250"
      - "16686:16686"
      - "16685:16685"
  gatewayprometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - ${PWD}/Gateway/prometheus-development.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    extra_hosts:
      - "host.docker.internal:host-gateway"
  databaseprometheus:
    image: "prom/prometheus"
    ports:
      - "9091:9090"
    volumes:
      - ${PWD}/Database/prometheus-development.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    extra_hosts:
      - "host.docker.internal:host-gateway"
  processingprometheus:
    image: "prom/prometheus"
    ports:
      - "9092:9090"
    volumes:
      - ${PWD}/Processing/prometheus-development.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    extra_hosts:
      - "host.docker.internal:host-gateway"
