version: '3.7'

services:
  gateway:
    container_name: "gateway"
    image: "gateway:latest"
    build:
      context: ./Gateway/
      dockerfile: ./Dockerfile
    networks:
      - example_network
    expose:
      - "80"
  database:
    container_name: "database"
    image: "database:latest"
    build:
      context: ./Database/
      dockerfile: ./Dockerfile
    networks:
      - example_network
  gateway:
    container_name: "processing"
    image: "processing:latest"
    build:
      context: ./Processing/
      dockerfile: ./Dockerfile
    networks:
      - example_network
  jaeger:
    image: "jaegertracing/all-in-one"
    networks:
      - example_network
  prometheus:
    image: "prom/prometheus"
    networks:
      - example_network

networks:
  example_network:
    driver: bridge
    name: example_network
