#                   
# This source file is part of the Collector-Analyst-Presenter Example open source project
# 
# SPDX-FileCopyrightText: 2021 Paul Schmiedmayer and the project authors (see CONTRIBUTORS.md) <paul.schmiedmayer@tum.de>
# 
# SPDX-License-Identifier: MIT
# 

global:
  scrape_interval: 15s
  scrape_timeout: 10s
scrape_configs:
  - job_name: 'processing'
    metrics_path: '/v1/metrics'
    static_configs:
      - targets:
         - 'processing:80'
