global:
  scrape_interval: 15s
  scrape_timeout: 10s
scrape_configs:
  - job_name: 'processing'
    metrics_path: '/v1/metrics'
    static_configs:
      - targets:
         - 'host.docker.internal:82'
