name: Build and Test

on:
  push:
    branches:
      - develop
      - release
  pull_request:
    branches:
      - develop
      - release

jobs:
  macosclient:
    name: macOS Client
    runs-on: macos-11
    defaults:
      run:
        working-directory: ./Client
    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: latest
    - name: Check Xcode version
      run: xcodebuild -version
    - name: Check Swift version
      run: swift --version
    - name: Build and test
      run: xcodebuild test -scheme Example -destination 'platform=iOS Simulator,OS=15.0,name=iPhone 12'
  macoswebservices:
    name: macOS ${{ matrix.webservice }}
    runs-on: macos-11
    strategy:
      matrix:
        webservice: [Gateway, Database, Processing]
    defaults:
      run:
        working-directory: ./${{ matrix.webservice }}
    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: latest
    - name: Check Xcode version
      run: xcodebuild -version
    - name: Check Swift version
      run: swift --version
    - name: Build and test
      run: swift test
  linuxwebservices:
    name: Linux ${{ matrix.webservice }} ${{ matrix.linux }}
    runs-on: ubuntu-latest
    container:
      image: swift:${{ matrix.linux }}
    strategy:
      matrix:
        webservice: [Gateway, Database, Processing]
        linux: [latest, focal, amazonlinux2, centos8]
    defaults:
      run:
        working-directory: ./${{ matrix.webservice }}
    steps:
    - uses: actions/checkout@v2
    - name: Install libsqlite3
      if: ${{ !(startsWith( matrix.linux, 'centos' ) || startsWith( matrix.linux, 'amazonlinux' )) }}
      run: apt-get update && apt-get install -y --no-install-recommends libsqlite3-dev
    - name: Install libsqlite3
      if: startsWith( matrix.linux, 'amazonlinux' )
      run: yum update -y && yum install -y sqlite-devel
    - name: Install libsqlite3
      if: startsWith( matrix.linux, 'centos' )
      run: yum update -y --nobest && yum install -y sqlite-devel
    - name: Check Swift version
      run: swift --version
    - name: Build and test
      run: swift test
