#                   
# This source file is part of the Collector-Analyst-Presenter Example open source project
# 
# SPDX-FileCopyrightText: 2021 Paul Schmiedmayer and the project authors (see CONTRIBUTORS.md) <paul.schmiedmayer@tum.de>
# 
# SPDX-License-Identifier: MIT
# 

name: Build Docker Image

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  docker:
    name: Docker Build and Push Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        webservice: [Gateway, Database, Processing]
    steps:
      - id: webservice
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ matrix.webservice }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get latest tag
        id: latesttag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: latest
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker imag
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.webservice }}
          push: true
          tags: ghcr.io/apodini/collectoranalystpresenterexample/${{ steps.webservice.outputs.lowercase }}:latest,ghcr.io/apodini/collectoranalystpresenterexample/${{ steps.webservice.outputs.lowercase }}:${{ steps.latesttag.outputs.tag }}
